### ISSUE TITLE
Doesn't discriminate on action cost?

### ISSUE THREAD

**Issue by JDeeth** [cpowell/cppGOAP#1]
If there's two actions with the same preconditions and effects but different costs, it doesn't choose the cheapest option. Instead it seems to choose the first option in the Actions vector.

From the war_game example (with typo fixed in scoutRunning):

```
  Action scout("scoutStealthily", 999);
  scout.setPrecondition(enemy_sighted, false);
  scout.setPrecondition(weapon_in_hand, true);
  scout.setEffect(enemy_sighted, true);
  actions.push_back(scout);

  Action run("scoutRunning", 15);
  run.setPrecondition(enemy_sighted, false);
  run.setPrecondition(weapon_in_hand, true);
  run.setEffect(enemy_sighted, true);
  actions.push_back(run);
```

As both actions do the same thing but scoutRunning costs less, I'd expect it to be selected - but instead scoutStealthily is always selected regardless of the costs! And if I put `actions.push_back(scout)` after `actions.push_back(run)` then scoutRunning is always selected regardless of the costs.

(I've spent the evening implementing multi-dimensional costs, so scoutStealthily can be slow and safe and scoutRunning can be fast but risky, and the agent can be configured to put more weight on the time cost vs the risk cost (vs the ammo cost vs the health cost... etc). But this error occurs with the code as provided.)

**Comment by cpowell** [comment]
Thank you very much for pointing this out. The fix turned out to be twofold:

1. Your patch's addition of "needle->action_ = &action;" That's a great catch.
2. Also getting rid of the known_nodes structure, which maintained a duplicate in-memory set of nodes that got out of sync with the open/closed lists.

Your fix was very helpful. Then, getting the end-of-run output to be correct depended on refactoring out known_nodes_. That's now done.
